# Generated by Django 3.2.23 on 2023-12-21 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_management_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes_table',
            name='note',
            field=models.FileField(upload_to=''),
        ),
    ]
