# Generated by Django 3.2.23 on 2023-12-21 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_management_app', '0002_alter_notes_table_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qp_table',
            name='year',
            field=models.CharField(max_length=20),
        ),
    ]
