# Generated by Django 3.2.23 on 2024-01-05 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_management_app', '0003_alter_qp_table_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='open_course_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('COURSE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_management_app.course_table')),
                ('SUBJECT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_management_app.subject_table')),
            ],
        ),
    ]
