# Generated by Django 3.2.23 on 2024-01-05 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_management_app', '0004_open_course_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject_table',
            name='COURSE',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course_management_app.course_table'),
        ),
    ]
