from django.contrib import admin
from django.urls import path,include

from course_management_app import views

urlpatterns = [
    path('', views.login, name='login'),
    path('login_code', views.login_code, name='login_code'),
    path('logout',views.logout),
    # --------------------------------- ADMIN ---------------------------------

    path('admin_home', views.admin_home,name='admin_home'),
    path('manage_teacher', views.manage_teacher, name='manage_teacher'),
    path('manage_course', views.manage_course, name='manage_course'),
    path('manage_subject', views.manage_subject, name='manage_subject'),
    path('open_course_admin', views.open_course_admin, name='open_course_admin'),
    path('manage_program', views.manage_program, name='manage_program'),
    path('manage_notification', views.manage_notification, name='manage_notification'),
    path('audit_course_admin', views.audit_course_admin, name='audit_course_admin'),
    path('audit_questions_admin/<int:id>', views.audit_questions_admin, name='audit_questions_admin'),
    path('add_course', views.add_course, name='add_course'),
    path('add_course_post', views.add_course_post, name='add_course_post'),
    path('add_subject', views.add_subject, name='add_subject'),
    path('add_subject_post', views.add_subject_post, name='add_subject_post'),
    path('add_open_course_admin', views.add_open_course_admin, name='add_open_course_admin'),
    path('add_open_course_post_admin', views.add_open_course_post_admin, name='add_open_course_post_admin'),
    path('add_notification', views.add_notification, name='add_notification'),
    path('add_notification_post', views.add_notification_post, name='add_notification_post'),
    path('add_program', views.add_program, name='add_program'),
    path('add_program_post', views.add_program_post, name='add_program_post'),
    path('add_teacher_post', views.add_teacher_post, name='add_teacher_post'),
    path('add_teacher', views.add_teacher, name='add_teacher'),
    path('add_audit_course', views.add_audit_course, name='add_audit_course'),
    path('add_audit_course_post', views.add_audit_course_post, name='add_audit_course_post'),
    path('add_audit_questions', views.add_audit_questions, name='add_audit_questions'),
    path('add_audit_questions_post', views.add_audit_questions_post, name='add_audit_questions_post'),
    path('complaints',views.complaints,name='complaints'),
    path('manage_subject_allocation',views.manage_subject_allocation,name='manage_subject_allocation'),
    path('subject_allocation', views.subject_allocation, name='subject_allocation'),
    path('subject_allocation_post', views.subject_allocation_post, name='subject_allocation_post'),
    path('view_news_events', views.view_news_events, name='view_news_events'),
    path('view_feedback', views.view_feedback, name='view_feedback'),
    path('view_notes', views.view_notes, name='view_notes'),
    path('view_qp', views.view_qp, name='view_qp'),
    path('view_students', views.view_students, name='view_students'),
    path('search_teacher', views.search_teacher, name='search_teacher'),
    path('search_course', views.search_course, name='search_course'),
    path('search_subject', views.search_subject, name='search_subject'),
    path('search_notes', views.search_notes, name='search_notes'),
    path('search_qp', views.search_qp, name='search_qp'),
    path('search_program_admin', views.search_program_admin, name='search_program_admin'),
    path('search_subject_allocation', views.search_subject_allocation, name='search_subject_allocation'),
    path('search_events', views.search_events, name='search_events'),
    path('search_students', views.search_students, name='search_students'),
    path('search_feedback', views.search_feedback, name='search_feedback'),
    path('search_complaint', views.search_complaint, name='search_complaint'),
    path('search_audit_admin', views.search_audit_admin, name='search_audit_admin'),
    path('search_open_course_admin', views.search_open_course_admin, name='search_open_course_admin'),
    path('search_audit_questions_admin', views.search_audit_questions_admin, name='search_audit_questions_admin'),
    path('search_notification', views.search_notification, name='search_notification'),
    path('edit_teacher/<int:id>', views.edit_teacher, name='edit_teacher'),
    path('edit_teacher_post', views.edit_teacher_post, name='edit_teacher_post'),
    path('delete_teacher/<int:id>', views.delete_teacher, name='delete_teacher'),
    path('edit_course/<int:id>', views.edit_course, name='edit_course'),
    path('edit_course_post', views.edit_course_post, name='edit_course_post'),
    path('delete_course/<int:id>', views.delete_course, name='delete_course'),
    path('edit_subject/<int:id>', views.edit_subject, name='edit_subject'),
    path('edit_subject_post', views.edit_subject_post, name='edit_subject_post'),
    path('delete_subject/<int:id>', views.delete_subject, name='delete_subject'),
    path('edit_program/<int:id>', views.edit_program, name='edit_program'),
    path('edit_program_post', views.edit_program_post, name='edit_program_post'),
    path('delete_program/<int:id>', views.delete_program, name='delete_program'),
    path('delete_subject_allocation/<int:id>', views.delete_subject_allocation, name='delete_subject_allocation'),
    path('delete_notification/<int:id>', views.delete_notification, name='delete_notification'),
    path('delete_audit_question/<int:id>', views.delete_audit_question, name='delete_audit_question'),
    path('delete_open_course_admin/<int:id>', views.delete_open_course_admin, name='delete_open_course_admin'),



    # --------------------------------- STAFF ---------------------------------


    path('staff_home',views.staff_home,name='staff_home'),
    path('manage_qp', views.manage_qp, name='manage_qp'),
    path('manage_notes', views.manage_notes, name='manage_notes'),
    path('manage_news_events', views.manage_news_events, name='manage_news_events'),
    path('open_course_staff', views.open_course_staff, name='open_course_staff'),
    path('add_news_events', views.add_news_events, name='add_news_events'),
    path('view_application', views.view_application, name='view_application'),
    path('accept_application/<int:id>', views.accept_application, name='accept_application'),
    path('reject_application/<int:id>', views.reject_application, name='reject_application'),
    path('view_complaints_staff', views.view_complaints_staff, name='view_complaints_staff'),
    path('view_programs', views.view_programs, name='view_programs'),
    path('send_reply/<int:id>', views.send_reply, name='send_reply'),
    path('send_reply_post', views.send_reply_post, name='send_reply_post'),
    path('view_feedback_staff', views.view_feedback_staff, name='view_feedback_staff'),
    path('view_students_staff', views.view_students_staff, name='view_students_staff'),
    path('audit_course_staff', views.audit_course_staff, name='audit_course_staff'),
    path('audit_questions_staff/<int:id>', views.audit_questions_staff, name='audit_questions_staff'),
    path('view_result', views.view_result, name='view_result'),
    path('add_open_course', views.add_open_course, name='add_open_course'),
    path('add_open_course_post', views.add_open_course_post, name='add_open_course_post'),
    path('add_qp', views.add_qp, name='add_qp'),
    path('add_qp_post', views.add_qp_post, name='add_qp_post'),
    path('add_notes', views.add_notes, name='add_notes'),
    path('add_notes_post', views.add_notes_post, name='add_notes_post'),
    path('add_news_events_post', views.add_news_events_post, name='add_news_events_post'),
    path('edit_qp/<int:id>', views.edit_qp, name='edit_qp'),
    path('edit_qp_post', views.edit_qp_post, name='edit_qp_post'),
    path('edit_note/<int:id>', views.edit_note, name='edit_note'),
    path('edit_note_post', views.edit_note_post, name='edit_note_post'),
    path('edit_news_event/<int:id>', views.edit_news_event, name='edit_news_event'),
    path('edit_news_event_post', views.edit_news_event_post, name='edit_news_event_post'),
    path('delete_qp/<int:id>', views.delete_qp, name='delete_qp'),
    path('delete_open_course_staff/<int:id>', views.delete_open_course_staff, name='delete_open_course_staff'),
    path('delete_note/<int:id>', views.delete_note, name='delete_note'),
    path('delete_news_event/<int:id>', views.delete_news_event, name='delete_news_event'),
    path('search_qp_staff', views.search_qp_staff, name='search_qp_staff'),
    path('search_notes_staff', views.search_notes_staff, name='search_notes_staff '),
    path('search_events_staff', views.search_events_staff, name='search_events_staff '),
    path('search_students_staff', views.search_students_staff, name='search_students_staff '),
    path('search_complaint_staff', views.search_complaint_staff, name='search_complaint_staff '),
    path('search_feedback_staff', views.search_feedback_staff, name='search_feedback_staff '),
    path('search_application', views.search_application, name='search_application '),
    path('search_audit_staff', views.search_audit_staff, name='search_audit_staff '),
    path('search_student', views.search_student, name='search_student '),
    path('search_program_staff', views.search_program_staff, name='search_program_staff '),
    path('search_audit_questions_staff', views.search_audit_questions_staff, name='search_audit_questions_staff '),
    path('search_open_course_staff', views.search_open_course_staff, name='search_open_course_staff '),

]
